<h1 style="color:#FFD700;">GOLD LAYER</h1>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Model evaluation; 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
df = pd.read_csv('silverlayerUSAccidents.csv')

Extracting features like month, day, and year from DateTime types is a critical step in preparing temporal data for analysis and modeling. It simplifies complex DateTime information, enhances interpretability, and empowers machine learning models to uncover meaningful insights and patterns in the data. This feature engineering process is especially valuable when dealing with time-center datasets.


In [5]:
df['Start_Time'] = df['Start_Time'].str.split('.').str[0]
df['End_Time'] = df['End_Time'].str.split('.').str[0]
df['Start_Time'] = pd.to_datetime(df['Start_Time'], format='%Y-%m-%d %H:%M:%S')
df['End_Time'] = pd.to_datetime(df['End_Time'], format='%Y-%m-%d %H:%M:%S')

In [7]:
df.head(10)

ID   Source  Severity          Start_Time            End_Time  Start_Lat  \
0   A-1  Source2         3 2016-02-08 05:46:00 2016-02-08 11:00:00  39.865147   
1   A-2  Source2         2 2016-02-08 06:07:59 2016-02-08 06:37:59  39.928059   
2   A-3  Source2         2 2016-02-08 06:49:27 2016-02-08 07:19:27  39.063148   
3   A-4  Source2         3 2016-02-08 07:23:34 2016-02-08 07:53:34  39.747753   
4   A-5  Source2         2 2016-02-08 07:39:07 2016-02-08 08:09:07  39.627781   
5   A-6  Source2         3 2016-02-08 07:44:26 2016-02-08 08:14:26  40.100590   
6   A-7  Source2         2 2016-02-08 07:59:35 2016-02-08 08:29:35  39.758274   
7   A-8  Source2         3 2016-02-08 07:59:58 2016-02-08 08:29:58  39.770382   
8   A-9  Source2         2 2016-02-08 08:00:40 2016-02-08 08:30:40  39.778061   
9  A-10  Source2         3 2016-02-08 08:10:04 2016-02-08 08:40:04  40.100590   

   Start_Lng  Distance(mi)                                        Description  \
0 -84.058723          0.01  Right lane blocked due to accident on I-70 Eas...   
1 -82.831184          0.01  Accident on Brice Rd at Tussing Rd. Expect del...   
2 -84.032608          0.01  Accident on OH-32 State Route 32 Westbound at ...   
3 -84.205582          0.01  Accident on I-75 Southbound at Exits 52 52B US...   
4 -84.188354          0.01  Accident on McEwen Rd at OH-725 Miamisburg Cen...   
5 -82.925194          0.01  Accident on I-270 Outerbelt Northbound near Ex...   
6 -84.230507          0.00  Accident on Oakridge Dr at Woodward Ave. Expec...   
7 -84.194901          0.01  Accident on I-75 Southbound at Exit 54B Grand ...   
8 -84.172005          0.00  Accident on Notre Dame Ave at Warner Ave. Expe...   
9 -82.925194          0.01  Right hand shoulder blocked due to accident on...   

                      Street  ... Station   Stop Traffic_Calming  \
0                     I-70 E  ...   False  False           False   
1                   Brice Rd  ...   False  False           False   
2             State Route 32  ...   False  False           False   
3                     I-75 S  ...   False  False           False   
4  Miamisburg Centerville Rd  ...   False  False           False   
5             Westerville Rd  ...   False  False           False   
6             N Woodward Ave  ...   False  False           False   
7                  N Main St  ...   False  False           False   
8             Notre Dame Ave  ...   False  False           False   
9             Westerville Rd  ...   False  False           False   

  Traffic_Signal Turning_Loop Sunrise_Sunset Civil_Twilight Nautical_Twilight  \
0          False        False          Night          Night             Night   
1          False        False          Night          Night             Night   
2           True        False          Night          Night               Day   
3          False        False          Night            Day               Day   
4           True        False            Day            Day               Day   
5          False        False            Day            Day               Day   
6          False        False            Day            Day               Day   
7          False        False            Day            Day               Day   
8          False        False            Day            Day               Day   
9          False        False            Day            Day               Day   

  Astronomical_Twilight  Weather_Bin  
0                 Night        Rainy  
1                   Day        Rainy  
2                   Day        Other  
3                   Day       Cloudy  
4                   Day       Cloudy  
5                   Day        Rainy  
6                   Day        Other  
7                   Day        Other  
8                   Day       Cloudy  
9                   Day        Rainy  

[10 rows x 44 columns]

In [9]:
print("\nUnique Start_Time values:")
print(df['Start_Time'].unique())
print("\nUnique End_Time values:")
print(df['End_Time'].unique())


Unique Start_Time values:
<DatetimeArray>
['2016-02-08 05:46:00', '2016-02-08 06:07:59', '2016-02-08 06:49:27',
 '2016-02-08 07:23:34', '2016-02-08 07:39:07', '2016-02-08 07:44:26',
 '2016-02-08 07:59:35', '2016-02-08 07:59:58', '2016-02-08 08:00:40',
 '2016-02-08 08:10:04',
 ...
 '2019-08-23 16:21:33', '2019-08-23 17:10:58', '2019-08-23 17:42:27',
 '2019-08-23 17:40:12', '2019-08-23 17:43:56', '2019-08-23 18:30:23',
 '2019-08-23 18:03:25', '2019-08-23 19:11:30', '2019-08-23 19:00:21',
 '2019-08-23 18:52:06']
Length: 4327617, dtype: datetime64[ns]

Unique End_Time values:
<DatetimeArray>
['2016-02-08 11:00:00', '2016-02-08 06:37:59', '2016-02-08 07:19:27',
 '2016-02-08 07:53:34', '2016-02-08 08:09:07', '2016-02-08 08:14:26',
 '2016-02-08 08:29:35', '2016-02-08 08:29:58', '2016-02-08 08:30:40',
 '2016-02-08 08:40:04',
 ...
 '2019-08-23 17:13:32', '2019-08-23 18:11:10', '2019-08-23 18:08:35',
 '2019-08-23 18:12:27', '2019-08-23 18:58:54', '2019-08-23 18:32:01',
 '2019-08-23 19:38:23', '

In [25]:
df.dtypes

ID                               object
Source                           object
Severity                          int64
Start_Time               datetime64[ns]
End_Time                 datetime64[ns]
Start_Lat                       float64
Start_Lng                       float64
Distance(mi)                    float64
Description                      object
Street                           object
City                             object
County                           object
State                            object
Zipcode                          object
Country                          object
Timezone                         object
Airport_Code                     object
Weather_Timestamp                object
Temperature(F)                   object
Wind_Chill(F)                   float64
Humidity(%)                      object
Pressure(in)                     object
Visibility(mi)                   object
Wind_Direction                   object
Wind_Speed(mph)                 float64


In [27]:
columns_with_night = df.columns[(df.isin(["Night",False]).any())]
columns_with_night

Index(['Distance(mi)', 'Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)',
       'Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit',
       'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming',
       'Traffic_Signal', 'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight',
       'Nautical_Twilight', 'Astronomical_Twilight'],
      dtype='object')

Data anomaly with 4 columns fix:

In [41]:
def find_columns_with_values(df, values):
    # Identify columns containing any of the specified values
    columns_with_values = df.columns[df.isin(values).any()]
    
    return columns_with_values

values_to_find = ['Night', False]

columns_with_night_or_false = find_columns_with_values(df, values_to_find)
print(columns_with_night_or_false)

Index(['Distance(mi)', 'Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)',
       'Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit',
       'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming',
       'Traffic_Signal', 'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight',
       'Nautical_Twilight', 'Astronomical_Twilight'],
      dtype='object')


In [45]:
columns = ['Distance(mi)', 'Wind_Chill(F)', 'Wind_Speed(mph)', 'Precipitation(in)',
           'Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit',
           'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming',
           'Traffic_Signal', 'Turning_Loop', 'Sunrise_Sunset', 'Civil_Twilight',
           'Nautical_Twilight', 'Astronomical_Twilight']

# Filter categorical columns
categorical_columns = [col for col in columns if df[col].dtype == 'object' or df[col].dtype == 'bool']
for col in categorical_columns:
    unique_values = df[col].unique()
    print(f"Unique values in '{col}':")
    for value in unique_values:
        print(value)
    print("\n" + "-"*50 + "\n")

Unique values in 'Amenity':
False
True

--------------------------------------------------

Unique values in 'Bump':
False
True

--------------------------------------------------

Unique values in 'Crossing':
False
True

--------------------------------------------------

Unique values in 'Give_Way':
False
True

--------------------------------------------------

Unique values in 'Junction':
False
True

--------------------------------------------------

Unique values in 'No_Exit':
False
True

--------------------------------------------------

Unique values in 'Railway':
False
True

--------------------------------------------------

Unique values in 'Roundabout':
False
True

--------------------------------------------------

Unique values in 'Station':
False
True

--------------------------------------------------

Unique values in 'Stop':
False
True

--------------------------------------------------

Unique values in 'Traffic_Calming':
False
True

--------------------------------

When using .isin(['Night', False]) to check for specific values, it's important to understand that this method is applied to all columns regardless of their data type. If a column is numeric, it will still be evaluated against the values ['Night', False], but only those values that can be compared (e.g., False as 0 in numeric columns) will yield a match.

Here’s why non-categorical columns appeared:

Numeric Columns:

False: In numeric columns, False is treated as 0. So if any numeric column has a 0, it matches False.
'Night': This string doesn’t match numeric columns, but the presence of False (or 0) may still be flagged.
Non-Categorical Columns:

Numeric columns can still contain 0 (which might be interpreted as False), thus being included in the result.

In [47]:
# Replace 'night' and 'false' with NaN to identify missing data and remove any non-relevant data
df['Distance(mi)'] = df['Distance(mi)'].replace(['night', 'false'], np.nan)
df['Wind_Chill(F)'] = df['Wind_Chill(F)'].replace(['night', 'false'], np.nan)
df['Wind_Speed(mph)'] = df['Wind_Speed(mph)'].replace(['night', 'false'], np.nan)
df['Precipitation(in)'] = df['Precipitation(in)'].replace(['night', 'false'], np.nan)

# Replace missing data with mean (no inplace=True and no chained indexing)
df['Distance(mi)'] = df['Distance(mi)'].fillna(df['Distance(mi)'].mean())
df['Wind_Chill(F)'] = df['Wind_Chill(F)'].fillna(df['Wind_Chill(F)'].mean())
df['Wind_Speed(mph)'] = df['Wind_Speed(mph)'].fillna(df['Wind_Speed(mph)'].mean())
df['Precipitation(in)'] = df['Precipitation(in)'].fillna(df['Precipitation(in)'].mean())

In [49]:
# Convert False/True to 0/1
boolean_columns = ['Amenity', 'Bump', 'Crossing', 'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station', 'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop']
for col in boolean_columns:
    df[col] = df[col].astype(str).str.lower().map({'false': 0, 'true': 1})

# Convert Night/Day to 0/1
twilight_columns = ['Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight', 'Astronomical_Twilight']
for col in twilight_columns:
    df[col] = df[col].astype(str).str.lower().map({'night': 0, 'day': 1})

specified_columns = boolean_columns + twilight_columns

# Convert each specified column to string type
for col in specified_columns:
    df[col] = df[col].astype(str)
    
unique_values = {col: df[col].unique() for col in specified_columns}

for col, values in unique_values.items():
    print(f"Unique values in {col}: {values}")

Unique values in Amenity: ['0' '1']
Unique values in Bump: ['0' '1']
Unique values in Crossing: ['0' '1']
Unique values in Give_Way: ['0' '1']
Unique values in Junction: ['0' '1']
Unique values in No_Exit: ['0' '1']
Unique values in Railway: ['0' '1']
Unique values in Roundabout: ['0' '1']
Unique values in Station: ['0' '1']
Unique values in Stop: ['0' '1']
Unique values in Traffic_Calming: ['0' '1']
Unique values in Traffic_Signal: ['0' '1']
Unique values in Turning_Loop: ['0']
Unique values in Sunrise_Sunset: ['0' '1']
Unique values in Civil_Twilight: ['0' '1']
Unique values in Nautical_Twilight: ['0' '1']
Unique values in Astronomical_Twilight: ['0' '1']


*NEW Feature Creation*

In [58]:
df['Accident_Duration'] = (df['End_Time'] - df['Start_Time']).dt.total_seconds() / 60.0
df['Accident_Duration'].head()

0    314.0
1     30.0
2     30.0
3     30.0
4     30.0
Name: Accident_Duration, dtype: float64

In [71]:
# Performing machine learning classification using the RandomForestClassifier on a sampled dataset.
# First, a random sample (10% of the original dataset) is taken and missing values are dropped.
# Categorical columns are then converted into numeric form using LabelEncoder to allow for numerical analysis.
# The features and target are defined, with the Severity column as the target.
# The dataset is split into training and testing sets, using 70% of the data for training and 30% for testing.
# A RandomForestClassifier is initialized and trained on the training data.

sampled_dff = df.sample(frac=0.1, random_state=42).dropna()

categorical_cols = sampled_dff.select_dtypes(include=['object', 'bool']).columns
label_encoder = LabelEncoder()
for col in categorical_cols:
    sampled_dff[col] = label_encoder.fit_transform(sampled_dff[col])
numeric_cols = sampled_dff.select_dtypes(include=['number']).columns
X = sampled_dff[numeric_cols].drop('Severity', axis=1, errors='ignore')
y = sampled_dff['Severity']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
rf_classifier = RandomForestClassifier(n_jobs=-1, random_state=42) 
rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.93
Confusion Matrix:
[[  1352    574     77      0]
 [   238 149489   3277    176]
 [    36   5139  18783      9]
 [     6   2476    356   2047]]
Classification Report:
              precision    recall  f1-score   support

           1       0.83      0.67      0.74      2003
           2       0.95      0.98      0.96    153180
           3       0.84      0.78      0.81     23967
           4       0.92      0.42      0.58      4885

    accuracy                           0.93    184035
   macro avg       0.88      0.71      0.77    184035
weighted avg       0.93      0.93      0.93    184035



Increase in precision and recall from silver layer
F1-scores also saw slight increases for Classes 1, 3, and 4, demonstrating overall better balance between precision and recall.
The accuracy remains stable at 93%, but macro-average scores (precision, recall, F1-score) suggest that the model's performance is more evenly distributed across the classes in the gold layer.

In [75]:
df.to_csv('goldlayerUSAccidents.csv', index=False)