# <font color="#4682B4">SILVER LAYER</font>



In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# For evaluation model;
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [3]:
df = pd.read_csv('bronzelayerUSAccidents.csv')

In [ ]:
input file= 
output file=

In [4]:
categorical_cols = df.select_dtypes(include=['object'])
categorical_cols.nunique()

ID                       6142287
Source                         3
Start_Time               4658253
End_Time                 5236843
Description              3057077
Street                    304134
City                       13263
County                      1846
State                         49
Zipcode                   705640
Country                        1
Timezone                       4
Airport_Code                2035
Weather_Timestamp         777575
Wind_Direction                24
Weather_Condition            142
Sunrise_Sunset                 2
Civil_Twilight                 2
Nautical_Twilight              2
Astronomical_Twilight          2
dtype: int64

In [5]:
# Display all unique elements
pd.set_option('display.max_rows', None)
print(df['Weather_Condition'].drop_duplicates())

0                                   Light Rain
2                                     Overcast
3                                Mostly Cloudy
10                                        Rain
20                                  Light Snow
81                                        Haze
89                            Scattered Clouds
92                               Partly Cloudy
93                                       Clear
134                                       Snow
138                     Light Freezing Drizzle
160                              Light Drizzle
162                                        Fog
242                                 Heavy Rain
243                        Light Freezing Rain
252                                     Cloudy
268                                    Drizzle
1135                        Light Freezing Fog
1597                                Light Haze
2379                                      Mist
2910                        Light Rain Showers
3742         

In [6]:
df2= df.copy()

In [16]:
total_elements = df2['Weather_Condition'].size
print(total_elements)

6142287


In [18]:
# This script processes a large CSV file containing US accident data by categorizing weather conditions into broader weather bins.
# It defines several weather categories (Clear, Cloudy, Rainy, Snowy, Windy, Hail, Volcanic Ash, Tornado) and maps detailed weather conditions to these categories.
# The data is read in chunks due to its large size, and each chunk is processed by mapping the 'Weather_Condition' to the defined bins.
# After processing, each chunk is saved as a separate CSV file.
# The 'Weather_Bin' column is converted to the 'category' datatype to optimize memory usage during processing.

weather_bins = {
    'Clear': ['Clear', 'Fair'],
    'Cloudy': ['Cloudy', 'Mostly Cloudy', 'Partly Cloudy', 'Scattered Clouds'],
    'Rainy': ['Light Rain', 'Rain', 'Light Freezing Drizzle', 'Light Drizzle', 'Heavy Rain', 'Light Freezing Rain', 'Drizzle', 'Light Freezing Fog', 'Light Rain Showers', 'Showers in the Vicinity', 'T-Storm', 'Thunder', 'Patches of Fog', 'Heavy T-Storm', 'Heavy Thunderstorms and Rain', 'Funnel Cloud', 'Heavy T-Storm / Windy', 'Heavy Thunderstorms and Snow', 'Rain / Windy', 'Heavy Rain / Windy', 'Squalls', 'Heavy Ice Pellets', 'Thunder / Windy', 'Drizzle and Fog', 'T-Storm / Windy', 'Smoke / Windy', 'Haze / Windy', 'Light Drizzle / Windy', 'Widespread Dust / Windy', 'Wintry Mix', 'Wintry Mix / Windy', 'Light Snow with Thunder', 'Fog / Windy', 'Snow and Thunder', 'Sleet / Windy', 'Heavy Freezing Rain / Windy', 'Squalls / Windy', 'Light Rain Shower / Windy', 'Snow and Thunder / Windy', 'Light Sleet / Windy', 'Sand / Dust Whirlwinds', 'Mist / Windy', 'Drizzle / Windy', 'Duststorm', 'Sand / Dust Whirls Nearby', 'Thunder and Hail', 'Freezing Rain / Windy', 'Light Snow Shower / Windy', 'Partial Fog', 'Thunder / Wintry Mix / Windy', 'Patches of Fog / Windy', 'Rain and Sleet', 'Light Snow Grains', 'Partial Fog / Windy', 'Sand / Dust Whirlwinds / Windy', 'Heavy Snow with Thunder', 'Heavy Blowing Snow', 'Low Drifting Snow', 'Light Hail', 'Light Thunderstorm', 'Heavy Freezing Drizzle', 'Light Blowing Snow', 'Thunderstorms and Snow', 'Heavy Rain Showers', 'Rain Shower / Windy', 'Sleet and Thunder', 'Heavy Sleet and Thunder', 'Drifting Snow / Windy', 'Shallow Fog / Windy', 'Thunder and Hail / Windy', 'Heavy Sleet / Windy', 'Sand / Windy', 'Heavy Rain Shower / Windy', 'Blowing Snow Nearby', 'Blowing Sand', 'Heavy Rain Shower', 'Drifting Snow', 'Heavy Thunderstorms with Small Hail'],
    'Snowy': ['Light Snow', 'Snow', 'Light Snow / Windy', 'Snow Grains', 'Snow Showers', 'Snow / Windy', 'Light Snow and Sleet', 'Snow and Sleet', 'Light Snow and Sleet / Windy', 'Snow and Sleet / Windy'],
    'Windy': ['Blowing Dust / Windy', 'Fair / Windy', 'Mostly Cloudy / Windy', 'Light Rain / Windy', 'T-Storm / Windy', 'Blowing Snow / Windy', 'Freezing Rain / Windy', 'Light Snow and Sleet / Windy', 'Sleet and Thunder / Windy', 'Blowing Snow Nearby', 'Heavy Rain Shower / Windy'],
    'Hail': ['Hail'],
    'Volcanic Ash': ['Volcanic Ash'],
    'Tornado': ['Tornado']
}

weather_mapping = {condition: bin_name for bin_name, bin_values in weather_bins.items() for condition in bin_values}

chunk_size = 61423  

chunks = pd.read_csv('bronzelayerUSAccidents.csv', chunksize=chunk_size)

for i, chunk in enumerate(chunks):
    chunk['Weather_Bin'] = chunk['Weather_Condition'].map(weather_mapping).fillna('Other')
    chunk['Weather_Bin'] = chunk['Weather_Bin'].astype('category')
    chunk.to_csv(f'processed_chunk_{i}.csv', index=False)

print("Processing complete.")

Processing complete.


In [20]:
df2.drop(columns=['Weather_Condition'], inplace=True)

In [26]:
df.columns

Index(['ID', 'Source', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat',
       'Start_Lng', 'Distance(mi)', 'Description', 'Street', 'City', 'County',
       'State', 'Zipcode', 'Country', 'Timezone', 'Airport_Code',
       'Weather_Timestamp', 'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)',
       'Pressure(in)', 'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [38]:
# Display all unique elements without truncation
pd.set_option('display.max_rows', None)  # Show all rows
print(df['Temperature(F)'].drop_duplicates())

0           36.9
1           37.9
2           36.0
3           35.1
6           34.0
8           33.3
9           37.4
10          35.6
12          33.8
23          37.0
27          39.9
29          39.2
31          34.2
34          33.1
36          23.0
38          22.8
39          26.6
40          21.0
42          19.9
43          25.0
46          26.1
47          24.8
50          21.9
53          21.2
57          22.5
67          32.0
70          27.0
71          16.2
72          15.8
74          15.4
75          14.0
76          15.1
78          16.0
81          17.6
83          17.1
89           7.0
92           6.1
93           5.0
94          12.0
97           9.0
98           7.5
102         18.0
104         10.9
106         18.5
109         21.6
115         19.0
119         25.5
125         10.0
126          8.1
129         12.9
142         24.1
158         30.9
160         33.6
161         32.9
165         32.2
179         30.0
192         31.1
199         32.4
201         30

In [30]:
df2['Temperature(F)'] = pd.cut(df2['Temperature(F)'],
                                     bins=[-100, 32, 60, 80, 100, 200],
                                     labels=['Freezing', 'Cold', 'Cool', 'Warm', 'Hot'])


In [42]:
print(df2['Temperature(F)'].value_counts())

Temperature(F)
Cool        2352590
Cold        2263565
Warm         951391
Freezing     554313
Hot           20424
Name: count, dtype: int64


In [48]:
df2['Humidity(%)'] = pd.cut(df2['Humidity(%)'],
                               bins=[0, 20, 40, 60, 80, 100],
                               labels=['Very Low', 'Low', 'Moderate', 'High', 'Very High'])


In [50]:
print(df2['Humidity(%)'].value_counts())

Humidity(%)
Very High    1943955
High         1733316
Moderate     1432513
Low           803041
Very Low      229462
Name: count, dtype: int64


In [52]:
# Display all unique elements
pd.set_option('display.max_rows', None)
print(df['Pressure(in)'].drop_duplicates())

0          29.68
1          29.65
2          29.67
3          29.64
5          29.63
6          29.66
9          29.62
25         29.60
27         29.61
38         29.69
41         29.71
42         29.75
55         29.73
62         29.70
67         29.58
71         29.95
72         29.87
75         29.89
76         29.92
77         29.96
78         29.91
79         29.97
80         29.93
87         30.14
88         30.03
89         30.22
90         30.18
91         30.12
93         30.20
94         30.08
95         30.24
97         30.26
98         30.28
100        30.27
102        30.16
104        30.29
105        30.31
106        30.32
109        30.30
112        30.33
114        30.34
116        30.35
118        30.04
119        30.11
123        30.13
124        30.25
125        30.54
126        30.48
127        30.49
128        30.57
129        30.53
131        30.52
132        30.50
135        30.23
136        30.09
138        30.06
139        30.02
143        30.01
146        30.

In [54]:
df2['Pressure(in)'] = pd.cut(df2['Pressure(in)'],
                                  bins=[0, 29.0, 29.9, 30.5, 100],
                                  labels=['Very Low', 'Low', 'Normal', 'High'])


In [56]:
print(df2['Pressure(in)'].value_counts())

Pressure(in)
Low         2973058
Normal      2107657
Very Low    1041862
High          19709
Name: count, dtype: int64


In [58]:
# Display all unique elements without truncation
pd.set_option('display.max_rows', None)  # Show all rows
print(df['Visibility(mi)'].drop_duplicates())

0           10.00
3            9.00
4            6.00
5            7.00
8            5.00
9            3.00
20           2.00
23           8.00
37           2.50
38           4.00
39           1.50
40           0.80
42           1.80
43           1.00
54           1.20
134          0.50
141          0.20
393          2.80
7280        15.00
11915        0.19
11956        4.20
14050       25.00
22820        0.12
26922       12.00
28465       20.00
36741        0.25
41002        0.10
41117        0.75
42258        0.40
49716        2.20
52823        0.00
59506        1.10
64919        3.50
65188       13.00
65581       11.00
71914        5.50
103524       1.40
119281      40.00
122668       0.63
127994       0.88
128174       0.38
130960      14.00
164627      30.00
170397      60.00
175263      50.00
265069       0.06
267559      80.00
282437      75.00
326313      65.00
345933     100.00
501827      19.00
523112      98.00
542597      70.00
546063      23.00
684838      16.00
745298    

In [60]:
df2['Visibility(mi)'] = pd.cut(df2['Visibility(mi)'],
                                    bins=[0, 0.5, 2, 10, 100],
                                    labels=['Very Poor', 'Poor', 'Moderate', 'Clear'])


In [62]:
print(df2['Visibility(mi)'].value_counts())

Visibility(mi)
Moderate     5782386
Poor          261043
Very Poor      70632
Clear          20484
Name: count, dtype: int64


In [65]:
# TO MEASURE THE ACCURACY OF DATA AFTER PROCESSING TO PREDICT THE TARGET VARIABLE, THE SEVERITY
# Performing machine learning classification using the RandomForestClassifier on a sampled dataset.
# First, a random sample (10% of the original dataset) is taken and missing values are dropped.
# Categorical columns are then converted into numeric form using LabelEncoder to allow for numerical analysis.
# The features and target are defined, with the Severity column as the target.
# The dataset is split into training and testing sets, using 70% of the data for training and 30% for testing.
# A RandomForestClassifier is initialized and trained on the training data.

sampled_dff = df.sample(frac=0.1, random_state=42).dropna()

categorical_cols = sampled_dff.select_dtypes(include=['object', 'bool']).columns
label_encoder = LabelEncoder()
for col in categorical_cols:
    sampled_dff[col] = label_encoder.fit_transform(sampled_dff[col])
numeric_cols = sampled_dff.select_dtypes(include=['number']).columns
X = sampled_dff[numeric_cols].drop('Severity', axis=1, errors='ignore')
y = sampled_dff['Severity']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)
rf_classifier = RandomForestClassifier(n_jobs=-1, random_state=42) 
rf_classifier.fit(X_train, y_train)
y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

confusion_mat = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_mat)

class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

Accuracy: 0.93
Confusion Matrix:
[[  1263    661     79      0]
 [   268 149362   3360    190]
 [    32   5343  18575     17]
 [     1   2491    364   2029]]
Classification Report:
              precision    recall  f1-score   support

           1       0.81      0.63      0.71      2003
           2       0.95      0.98      0.96    153180
           3       0.83      0.78      0.80     23967
           4       0.91      0.42      0.57      4885

    accuracy                           0.93    184035
   macro avg       0.87      0.70      0.76    184035
weighted avg       0.93      0.93      0.93    184035



The silver layer seems to handle Class 4 (Critical severity) slightly better, which could be important for high-risk accident prediction

In [68]:
df2.to_csv('silverlayerUSAccidents.csv', index=False)